### ISSUE TITLE
Report slice info to GMOC

### ISSUE THREAD

**Issue by tcmitchell** [ahelsing/tickettest2#201] opened 2015-05-19 03:06 UTC
The SA should report slice related info (creation, expiration, people) to GMOC.

 _Imported from trac ticket [#201](http://trac.gpolab.bbn.com/proto-ch/ticket/201),  created by tmitchel on 09-04-2012 at 14:46, last modified: 09-11-2012 at 13:49_

**Comment by seledwards** [comment] 2015-05-19 03:06
This is a duplicate of #181.

_Trac comment by sedwards (github user: seledwards) on 09-11-2012 at 13:49_

**Closed by seledwards** 2015-05-19 03:06 UTC
Labels: duplicate, sa, task
